version: '3'

services:
  mysql_db:
    container_name: mysql_db_u 
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: practica03
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - "33:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: